name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          echo "USER=${{ sercets.VM_USER }}" 
          echo "HOST=${{ secrets.VM_HOST }}" 
          ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << EOF
            set -e

            cd ~/flask-api

            echo "📦 Save current version"
            git rev-parse HEAD > previous_version.txt

            git pull

            echo "🔨 Build"
            docker compose build

            echo "🚀 Start"
            docker compose up -d

            echo "⏳ Wait"
            sleep 5

            echo "🧪 Healthcheck"
            curl -fk https://localhost/health

            echo "✅ Deploy OK"
          EOF
